# Generated by Django 4.0.5 on 2022-09-19 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatahubDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governing_law', models.TextField()),
                ('warranty', models.TextField()),
                ('limitations_of_liabilities', models.TextField()),
                ('privacy_policy', models.TextField()),
                ('tos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('org_email', models.CharField(max_length=255, unique=True)),
                ('address', models.JSONField()),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/', validators=[utils.validators.validate_file_size, utils.validators.validate_image_type])),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='organizations/logos/', validators=[utils.validators.validate_file_size, utils.validators.validate_image_type])),
                ('org_description', models.TextField(blank=True, max_length=512, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserOrganizationMap',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datahub.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('category', models.JSONField()),
                ('geography', models.CharField(blank=True, max_length=255)),
                ('crop_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('constantly_update', models.BooleanField(default=False)),
                ('age_of_date', models.CharField(blank=True, max_length=255, null=True)),
                ('data_capture_start', models.DateTimeField(blank=True, null=True)),
                ('data_capture_end', models.DateTimeField(blank=True, null=True)),
                ('dataset_size', models.CharField(blank=True, max_length=255, null=True)),
                ('connector_availability', models.CharField(blank=True, max_length=255, null=True)),
                ('sample_dataset', models.FileField(blank=True, upload_to='users/datasets/sample_data/', validators=[utils.validators.validate_file_size])),
                ('status', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('for_review', 'for_review')], default='for_review', max_length=255, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True)),
                ('user_map', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datahub.userorganizationmap')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
