# Generated by Django 4.0.5 on 2023-01-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0005_datasetv2_datasetv2_datahub_dat_name_b33e13_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetv2',
            name='geography',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datasetv2',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
