# Generated by Django 4.0.5 on 2023-01-04 20:18

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0007_alter_datasetv2_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetV2File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,  primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='users/datasets/sample_data/')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='datahub.datasetv2')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
