# Generated by Django 4.0.5 on 2023-01-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0012_remove_datasetv2_datahub_dat_name_b33e13_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetv2file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
