# Generated by Django 4.0.5 on 2023-01-12 21:50

import datahub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0013_alter_datasetv2file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetv2file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=datahub.models.DatasetV2File.dataset_directory_path),
        ),
    ]
