# Generated by Django 4.1.5 on 2023-01-27 09:12

import datahub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0014_alter_datasetv2file_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasetv2file",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=datahub.models.DatasetV2File.dataset_directory_path,
            ),
        ),
    ]
