# Generated by Django 4.1.5 on 2023-01-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0015_alter_datasetv2file_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasetv2",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
