# Generated by Django 4.1.5 on 2023-03-14 10:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0016_alter_datasetv2_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardisationTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("datapoint_category", models.CharField(max_length=50, unique=True)),
                ("datapoint_description", models.TextField(max_length=255)),
                ("datapoint_attributes", models.JSONField(default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
