# Generated by Django 4.0.5 on 2023-04-07 06:27

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0019_policy_datasetv2file_accessibility_usagepolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='file',
            field=models.FileField(upload_to='media/policy/', validators=[utils.validators.validate_25MB_file_size]),
        ),
    ]
