# Generated by Django 4.0.5 on 2023-04-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0020_alter_policy_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsagePolicy',
        ),
    ]
