# Generated by Django 4.1.5 on 2023-04-08 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("datahub", "0023_alter_datasetv2file_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datasetv2",
            old_name="status",
            new_name="is_temp",
        ),
        migrations.AlterField(
            model_name="datasetv2file",
            name="dataset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datasets",
                to="datahub.datasetv2",
            ),
        ),
    ]
