# Generated by Django 4.0.5 on 2023-04-11 05:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0023_alter_datasetv2file_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsagePolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_status', models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected')], default='public', max_length=255, null=True)),
                ('accessibility_time', models.DateField(null=True)),
                ('dataset_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_file', to='datahub.datasetv2file')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org', to='datahub.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
