# Generated by Django 4.0.5 on 2023-04-11 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0024_usagepolicy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetv2file',
            name='accessibility',
        ),
    ]
