# Generated by Django 4.0.5 on 2023-04-11 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0026_datasetv2file_accessibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagepolicy',
            name='accessibility_time',
            field=models.DateField(default=datetime.date(2023, 5, 9)),
        ),
        migrations.AlterField(
            model_name='usagepolicy',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('requested', 'requested')], default='requested', max_length=255, null=True),
        ),
    ]
