# Generated by Django 4.0.5 on 2023-04-13 04:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0030_alter_datasetv2_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usagepolicy',
            name='org_id',
        ),
        migrations.AddField(
            model_name='usagepolicy',
            name='user_organization_map',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='org', to='datahub.userorganizationmap'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usagepolicy',
            name='accessibility_time',
            field=models.DateField(default=datetime.date(2023, 5, 11)),
        ),
    ]
