# Generated by Django 4.0.5 on 2023-04-13 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0031_remove_usagepolicy_org_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagepolicy',
            name='user_organization_map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='org', to='datahub.userorganizationmap'),
        ),
    ]
