# Generated by Django 4.0.5 on 2023-04-13 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0032_alter_usagepolicy_user_organization_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagepolicy',
            name='user_organization_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org', to='datahub.userorganizationmap'),
        ),
    ]
