# Generated by Django 4.0.5 on 2023-04-19 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0034_datasetv2_geography_new_alter_datasetv2file_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetv2',
            name='geography',
        ),
    ]
