# Generated by Django 4.0.5 on 2023-04-19 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0035_remove_datasetv2_geography'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasetv2',
            old_name='geography_new',
            new_name='geography',
        ),
    ]
