# Generated by Django 4.0.5 on 2023-04-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0036_rename_geography_new_datasetv2_geography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetv2file',
            name='source',
            field=models.CharField(choices=[('file', 'file'), ('mysql', 'mysql'), ('postgresql', 'postgresql'), ('live_api', 'live_api')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usagepolicy',
            name='accessibility_time',
            field=models.DateField(null=True),
        ),
    ]
