# Generated by Django 4.1.5 on 2023-08-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0040_alter_datasetv2_name_alter_policy_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagepolicy',
            name='api_key',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usagepolicy',
            name='type',
            field=models.CharField(choices=[('dataset_file', 'dataset_file'), ('api', 'api')], default='dataset_file', max_length=255, null=True),
        ),
    ]
