# Generated by Django 4.1.5 on 2023-08-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0044_merge_20230816_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcefile',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
