# Generated by Django 4.1.5 on 2023-08-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0045_resourcefile_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.JSONField(default=dict),
        ),
    ]
