# Generated by Django 4.1.5 on 2023-08-18 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0048_merge_20230818_0954"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datasetv2file",
            name="connection_details",
        ),
        migrations.DeleteModel(
            name="DatasetV2FileReload",
        ),
    ]
