# Generated by Django 4.1.5 on 2023-08-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0052_alter_resource_description_alter_resource_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
