# Generated by Django 4.1.5 on 2023-09-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0056_alter_resourcefile_transcription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcefile",
            name="transcription",
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
