# Generated by Django 4.1.5 on 2024-01-13 08:27

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0062_alter_subcategory_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="LangchainPgCollection",
            fields=[
                ("name", models.CharField(max_length=50)),
                ("cmetadata", models.JSONField()),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "resource_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resource_file_collections",
                        to="datahub.resourcefile",
                    ),
                ),
            ],
            options={
                "db_table": "datahub_langchain_pg_collection",
            },
        ),
        migrations.CreateModel(
            name="LangchainPgEmbedding",
            fields=[
                ("embedding", pgvector.django.VectorField(verbose_name=1563)),
                ("document", models.TextField()),
                ("cmetadata", models.JSONField()),
                ("custom_id", models.CharField(max_length=255)),
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "collection_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="datahub.langchainpgcollection",
                    ),
                ),
            ],
            options={
                "db_table": "datahub_langchain_pg_embedding",
            },
        ),
    ]
