# Generated by Django 4.1.5 on 2024-01-25 05:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0066_alter_resourcefile_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourceusagepolicy",
            name="type",
            field=models.CharField(
                choices=[("resource", "resource"), ("embeddings", "embeddings")],
                default="resource",
                max_length=200,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Messages",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "bot_type",
                    models.CharField(
                        choices=[
                            ("whatsapp", "whatsapp"),
                            ("telegram", "telegram"),
                            ("vistaar", "vistaar"),
                        ],
                        default="vistaar",
                        max_length=10,
                    ),
                ),
                ("bot_reference", models.CharField(max_length=50, null=True)),
                ("query", models.CharField(max_length=10000, null=True)),
                ("translated_message", models.CharField(max_length=10000, null=True)),
                ("query_response", models.CharField(max_length=10000, null=True)),
                ("feedback", models.CharField(max_length=4096, null=True)),
                (
                    "input_type",
                    models.CharField(
                        choices=[("text", "text"), ("voice", "voice")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("input_language_detected", models.CharField(max_length=20, null=True)),
                ("condensed_question", models.CharField(max_length=20000, null=True)),
                (
                    "resource",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages_resource",
                        to="datahub.resource",
                    ),
                ),
                (
                    "retrieved_chunks",
                    models.ManyToManyField(to="datahub.langchainpgembedding"),
                ),
                (
                    "user_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_user_map",
                        to="datahub.userorganizationmap",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
