# Generated by Django 4.1.5 on 2024-01-31 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0069_alter_messages_bot_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="langchainpgembedding",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="datahub.langchainpgcollection",
            ),
        ),
    ]
