# Generated by Django 4.1.5 on 2024-06-25 17:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0077_alter_resource_description_alter_resource_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='countries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='resource',
            name='sub_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, null=True, size=None),
        ),
    ]
