# Generated by Django 4.1.5 on 2024-07-15 08:43

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0080_alter_subcategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='file',
            field=models.FileField(null=True, upload_to='https://.s3.amazonaws.com/policy/', validators=[utils.validators.validate_25MB_file_size]),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='file',
            field=models.FileField(blank=True, max_length=2000, null=True, upload_to='users/resources/'),
        ),
    ]
