# Generated by Django 4.1.5 on 2024-09-19 10:26

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0081_alter_policy_file_alter_resourcefile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='district',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='state',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='village',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='file',
            field=models.FileField(null=True, upload_to='https://platform-farmer-dev.s3.amazonaws.com/policy/', validators=[utils.validators.validate_25MB_file_size]),
        ),
    ]
