# Generated by Django 4.1.5 on 2023-06-05 12:15

from django.db import migrations, models
import django.db.models.deletion
import utils.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0040_alter_datasetv2_name_alter_policy_description_and_more'),
        ('participant', '0002_project_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicketV2',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('category', models.CharField(choices=[('connectors', 'connectors'), ('datasets', 'datasets'), ('others', 'others'), ('user_accounts', 'user_accounts'), ('usage_policy', 'usage_policy'), ('certificate', 'certificate')], max_length=255)),
                ('ticket_attachment', models.FileField(blank=True, null=True, upload_to='support_ticket/support/', validators=[utils.validators.validate_file_size])),
                ('status', models.CharField(choices=[('open', 'open'), ('hold', 'hold'), ('closed', 'closed')], default='closed', max_length=255)),
                ('user_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datahub.userorganizationmap')),
            ],
            options={
                'db_table': 'support_ticket_v2',
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resolution_text', models.CharField(max_length=1000)),
                ('solution_attachments', models.FileField(blank=True, null=True, upload_to='support_resolutions/resolutions/', validators=[utils.validators.validate_file_size])),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.supportticketv2')),
            ],
            options={
                'db_table': 'resolution',
            },
        ),
    ]
