# Generated by Django 4.1.5 on 2023-10-19 07:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedBack",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("message_id", models.UUIDField()),
                ("phone_number", models.CharField(max_length=15, null=True)),
                ("user_query", models.TextField()),
                ("translated_query", models.TextField(null=True)),
                ("response", models.TextField(null=True)),
                ("translated_response", models.TextField(null=True)),
                ("message_feedback", models.JSONField(default=dict, null=True)),
                ("video_feedback", models.JSONField(default=dict, null=True)),
                ("video_url", models.CharField(max_length=150, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
