# Generated by Django 4.1.5 on 2025-03-17 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microsite', '0002_inspection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inspection',
        ),
    ]
