# Generated by Django 4.0.5 on 2022-09-19 11:08

from django.db import migrations, models
import django.db.models.deletion
import utils.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datahub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connectors',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connector_name', models.CharField(max_length=255, unique=True)),
                ('connector_type', models.CharField(max_length=255)),
                ('connector_description', models.CharField(blank=True, max_length=500, null=True)),
                ('docker_image_url', models.CharField(max_length=255)),
                ('application_port', models.IntegerField()),
                ('certificate', models.FileField(blank=True, upload_to='users/connectors/certificates/', validators=[utils.validators.validate_file_size])),
                ('usage_policy', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('connector_status', models.CharField(default='install certificate', max_length=255)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datahub.datasets')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255, unique=True)),
                ('department_discription', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datahub.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('connectors', 'connectors'), ('datasets', 'datasets'), ('others', 'others'), ('user_accounts', 'user_accounts'), ('usage_policy', 'usage_policy'), ('certificate', 'certificate')], max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('issue_message', models.CharField(max_length=1000, null=True)),
                ('issue_attachments', models.FileField(blank=True, null=True, upload_to='users/tickets/', validators=[utils.validators.validate_file_size])),
                ('solution_message', models.CharField(max_length=1000, null=True)),
                ('solution_attachments', models.FileField(blank=True, null=True, upload_to='users/tickets/soluctions/', validators=[utils.validators.validate_file_size])),
                ('status', models.CharField(choices=[('open', 'open'), ('hold', 'hold'), ('closed', 'closed')], max_length=255)),
                ('user_map', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datahub.userorganizationmap')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255, unique=True)),
                ('project_discription', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConnectorsMap',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connector_pair_status', models.CharField(default='awaiting for approval', max_length=255)),
                ('ports', models.JSONField(default={})),
                ('status', models.BooleanField(default=True)),
                ('consumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumer', to='participant.connectors')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider', to='participant.connectors')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='connectors',
            name='department',
            field=models.ForeignKey(default='e459f452-2b4b-4129-ba8b-1e1180c87888', on_delete=django.db.models.deletion.PROTECT, to='participant.department'),
        ),
        migrations.AddField(
            model_name='connectors',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='participant.project'),
        ),
        migrations.AddField(
            model_name='connectors',
            name='user_map',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='datahub.userorganizationmap'),
        ),
    ]
