# Generated by Django 4.1.5 on 2023-06-06 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0040_alter_datasetv2_name_alter_policy_description_and_more'),
        ('participant', '0003_supportticketv2_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='user_map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datahub.userorganizationmap'),
        ),
    ]
