# Generated by Django 4.1.5 on 2023-07-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participant", "0004_resolution_user_map"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportticketv2",
            name="status",
            field=models.CharField(
                choices=[("open", "open"), ("hold", "hold"), ("closed", "closed")],
                default="open",
                max_length=255,
            ),
        ),
    ]
