# Generated by Django 4.0.5 on 2023-04-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_on_boarded_by_alter_userrole_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='approval_status',
            field=models.BooleanField(default=True),
        ),
    ]
