# Generated by Django 4.0.5 on 2023-03-11 08:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datahub', '0016_alter_datasetv2_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connectors',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=512)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConnectorsMap',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition', models.JSONField()),
                ('status', models.BooleanField(default=True)),
                ('connectors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectors.connectors')),
                ('left_dataset_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_dataset_file', to='datahub.datasetv2file')),
                ('right_dataset_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_dataset_file', to='datahub.datasetv2file')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
