# Generated by Django 4.0.5 on 2023-03-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectors',
            name='integrated_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='media/connectors/'),
        ),
    ]
