# Generated by Django 4.0.5 on 2023-04-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0004_alter_connectors_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectorsmap',
            name='condition',
            field=models.JSONField(default=dict),
        ),
    ]
