# Generated by Django 4.1.5 on 2023-07-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0005_alter_connectorsmap_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectors",
            name="config",
            field=models.JSONField(default=dict),
        ),
    ]
