# Generated by Django 4.1.5 on 2024-09-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0007_alter_connectors_integrated_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectors',
            name='integrated_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='https://platform-farmer-dev.s3.amazonaws.com/connectors/'),
        ),
    ]
