# Generated by Django 4.0.5 on 2023-01-04 11:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0004_alter_datasets_sample_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetV2',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.JSONField()),
                ('geography', models.CharField(blank=True, max_length=255)),
                ('data_capture_start', models.DateTimeField(blank=True, null=True)),
                ('data_capture_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('dataset', models.FileField(upload_to='users/datasets/sample_data/')),
                ('user_map', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datahub.userorganizationmap')),
            ],
        ),
        migrations.AddIndex(
            model_name='datasetv2',
            index=models.Index(fields=['name'], name='datahub_dat_name_b33e13_idx'),
        ),
    ]
