# Generated by Django 4.0.5 on 2023-01-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0009_remove_datasetv2_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetv2',
            name='constantly_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datasetv2file',
            name='source',
            field=models.CharField(choices=[('file', 'file'), ('mysql', 'mysql'), ('postgresql', 'postgresql')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
