# Generated by Django 4.0.5 on 2023-01-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0010_datasetv2_constantly_update_datasetv2file_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetv2file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/users/datasets/datasets/'),
        ),
    ]
