# Generated by Django 4.1.5 on 2023-03-22 11:54

import datahub.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datahub", "0017_standardisationtemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetv2file",
            name="standardised_configuration",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="datasetv2file",
            name="standardised_file",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=datahub.models.DatasetV2File.dataset_directory_path,
            ),
        ),
    ]
