# Generated by Django 4.0.5 on 2023-04-07 06:27

import uuid

import django.db.models.deletion
from django.db import migrations, models

import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0018_datasetv2file_standardised_configuration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=512)),
                ('file', models.ImageField(upload_to='media/policy/', validators=[utils.validators.validate_25MB_file_size])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='datasetv2file',
            name='accessibility',
            field=models.CharField(choices=[('public', 'public'), ('registered', 'registered'), ('private', 'private')], default='public', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='UsagePolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_status', models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected')], default='public', max_length=255, null=True)),
                ('accessibility_time', models.DateField(null=True)),
                ('dataset_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dataset_file', to='datahub.datasetv2file')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org', to='datahub.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
