# Generated by Django 4.0.5 on 2023-04-07 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0022_delete_usagepolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetv2file',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
