# Generated by Django 4.0.5 on 2023-04-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0024_rename_status_datasetv2_is_temp_and_more'),
        ('datahub', '0028_alter_usagepolicy_dataset_file'),
    ]

    operations = [
    ]
