# Generated by Django 4.1.5 on 2023-05-02 10:31

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("datahub", "0039_alter_datasetv2_user_map"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasetv2",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="policy",
            name="description",
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name="policy",
            name="file",
            field=models.FileField(
                null=True,
                upload_to="media/policy/",
                validators=[utils.validators.validate_25MB_file_size],
            ),
        ),
    ]
