# Generated by Django 4.1.5 on 2023-08-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0041_resource_resourcefile"),
        ("datahub", "0043_alter_usagepolicy_api_key"),
    ]

    operations = []
