# Generated by Django 4.1.5 on 2023-08-17 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0045_resourcefile_file_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetv2file",
            name="connection_details",
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name="DatasetV2FileReload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dataset_file",
                        to="datahub.datasetv2file",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
