# Generated by Django 4.1.5 on 2023-08-18 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0046_resource_category"),
        ("datahub", "0047_alter_datasetv2file_connection_details"),
    ]

    operations = []
