# Generated by Django 4.1.5 on 2023-08-18 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0049_remove_datasetv2file_connection_details_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="category",
        ),
        migrations.AddField(
            model_name="datasetv2file",
            name="connection_details",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.CreateModel(
            name="DatasetV2FileReload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dataset_file",
                        to="datahub.datasetv2file",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
