# Generated by Django 4.1.5 on 2023-08-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0050_remove_resource_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.JSONField(default=dict),
        ),
    ]
