# Generated by Django 4.1.5 on 2024-01-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0061_alter_datasetsubcategorymap_dataset_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
