# Generated by Django 4.1.5 on 2024-01-17 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0063_langchainpgcollection_langchainpgembedding"),
    ]

    operations = [
        migrations.RenameField(
            model_name="langchainpgcollection",
            old_name="id",
            new_name="uuid",
        ),
        migrations.RenameField(
            model_name="langchainpgembedding",
            old_name="collection_id",
            new_name="collection",
        ),
        migrations.RemoveField(
            model_name="langchainpgcollection",
            name="resource_file",
        ),
        migrations.AlterModelTable(
            name="langchainpgcollection",
            table="langchain_pg_collection",
        ),
        migrations.AlterModelTable(
            name="langchainpgembedding",
            table="langchain_pg_embedding",
        ),
    ]
