# Generated by Django 4.1.5 on 2024-01-18 05:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0064_rename_id_langchainpgcollection_uuid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceUsagePolicy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("resourse_file", "resourse_file"),
                            ("resource_api", "resource_api"),
                            ("embeddings", "embeddings"),
                        ],
                        default="resourse_file",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("requested", "requested"),
                        ],
                        default="requested",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("accessibility_time", models.DateField(null=True)),
                ("api_key", models.CharField(max_length=64, null=True, unique=True)),
                ("configs", models.JSONField(default=dict, null=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_usage_policy",
                        to="datahub.resource",
                    ),
                ),
                (
                    "user_organization_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="org_usage_policy",
                        to="datahub.userorganizationmap",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
