# Generated by Django 4.1.5 on 2024-01-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0065_resourceusagepolicy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcefile",
            name="type",
            field=models.CharField(
                choices=[("youtube", "youtube"), ("pdf", "pdf"), ("file", "file")],
                default="file",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="resourceusagepolicy",
            name="type",
            field=models.CharField(
                choices=[("resource", "resource"), ("embeddings", "embeddings")],
                default="resource",
                max_length=20,
                null=True,
            ),
        ),
    ]
