# Generated by Django 4.1.5 on 2024-01-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0068_alter_messages_retrieved_chunks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="bot_type",
            field=models.CharField(
                choices=[
                    ("whatsapp", "whatsapp"),
                    ("telegram", "telegram"),
                    ("vistaar", "vistaar"),
                    ("vistaar_api", "vistaar_api"),
                ],
                default="vistaar",
                max_length=20,
            ),
        ),
    ]
