# Generated by Django 4.1.5 on 2024-02-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0070_alter_langchainpgembedding_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="accessibility",
            field=models.CharField(
                choices=[
                    ("public", "public"),
                    ("registered", "registered"),
                    ("private", "private"),
                ],
                default="public",
                max_length=255,
                null=True,
            ),
        ),
    ]
