# Generated by Django 4.1.5 on 2024-02-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0071_resource_accessibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcefile",
            name="embeddings_status",
            field=models.CharField(
                choices=[
                    ("completed", "completed"),
                    ("in-progress", "in-progress"),
                    ("failed", "failed"),
                ],
                default="in-progress",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resourcefile",
            name="embeddings_status_reason",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="resourcefile",
            name="type",
            field=models.CharField(
                choices=[
                    ("youtube", "youtube"),
                    ("pdf", "pdf"),
                    ("file", "file"),
                    ("website", "website"),
                    ("api", "api"),
                ],
                default="file",
                max_length=20,
                null=True,
            ),
        ),
    ]
