# Generated by Django 4.1.5 on 2024-02-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0073_messages_prompt_usage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcefile",
            name="transcription",
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
