# Generated by Django 4.1.5 on 2024-05-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datahub", "0074_alter_resourcefile_transcription"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="output",
            field=models.JSONField(default={}, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="country",
            field=models.TextField(max_length=250, null=True),
        ),
    ]
