# Generated by Django 4.1.5 on 2024-06-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0076_alter_resourcefile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
