# Generated by Django 4.1.5 on 2024-06-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0079_subcategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
