# Generated by Django 4.1.5 on 2025-03-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0083_organization_country_organization_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefile',
            name='type',
            field=models.CharField(choices=[('youtube', 'youtube'), ('pdf', 'pdf'), ('file', 'file'), ('website', 'website'), ('api', 'api'), ('s3', 's3'), ('google_drive', 'google_drive'), ('dropbox', 'dropbox'), ('azure_blob', 'azure_blob')], default='file', max_length=20, null=True),
        ),
    ]
