# Generated by Django 4.1.5 on 2025-03-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0084_alter_resourcefile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceusagepolicy',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('requested', 'requested'), ('recalled', 'recalled')], default='requested', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usagepolicy',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('requested', 'requested'), ('recalled', 'recalled')], default='requested', max_length=255, null=True),
        ),
    ]
